from BinarySearchTreeADT import BinarySearchTreeADT

class LinkedBinarySearchTree(BinarySearchTreeADT):
  def count_internal(self) -> int: ...
  def degree(self, key: object) -> int: ...
  def height(self, key: object) -> int: ...
  def level(self, key: object) -> int: ...
  def ancestor(self, key: object) -> str: ...